### ISSUE TITLE
Computation of v_norm wrong?

### ISSUE THREAD

**Issue by SamiBidier** [thunil/Deep-Flow-Prediction#13]
Hi,
pls correct me if i'm wrong, but I think there is a small error in the data normalisation, where the norm of v is computed with the pressure values instead of v1. 

Would be glad if you could verify.
Thanks

https://github.com/thunil/Deep-Flow-Prediction/blob/c3123d1bac6e79fca0d3bba5bcc32cd08bd16464/train/dataset.py#L117

**Comment by thunil** [comment]
Good question, but the code is correct. The inputs are [in-x, in-y, mask], and hence indices 0 and 1 are used for computing v_norm.

**Comment by SamiBidier** [comment]
thanks! understood, my mistake

**Comment by thunil** [comment]
No worries, thanks for checking! It's easy to get wrong, it's actually explained incorrectly here at the moment: http://physicsbaseddeeplearning.org/supervised-airfoils.html (will also be fixed soon).
