### ISSUE TITLE
Issues loading data and loading pre-trained model

### ISSUE THREAD

**Issue by zizi96** [thunil/Deep-Flow-Prediction#4]
Hi, I have 2 questions regarding running the models. 

1. 

The 1st is do do with training a model from scratch. When setting prop, what effect do the values given in line 38 of dataset.py have? I assume they mix the data in different proportions from the different directories however I'm not sure what the 1000 value does if this is the case.

2. 

I'm also trying to implement the given pre-trained models.

I'm trying to input a batch of test data into the  model. This is what the models predicting, it doesn't seem to [predict any of the flow fields](https://imgur.com/a/bEtlhyr).

I suspect the issue is due to the model not compiling properly but I'm not sure.
To compile the model I had to switch the compiling method to strict when running runTest.py (line 72). 
When running the code unedited, I received a Run time error loading `state_dict` due to missing keys - `"layer2b.layer2b_conv.weight", "layer2b.layer2b_conv.bias",...` and unexpected keys - `"layer2x.layer2x_conv.weight", "layer2x.layer2x_conv.bias",...`

Could you advise on how I should resolve these issues?

**Comment by thunil** [comment]
Hi, L38 of dataset.py controls the mix of data from 3 directories. By default /reg, /shear, and /sup. E.g., you can pass [100, 0.7,0,0.3] which would mean there are 100 samples in total, and load 70 from "reg" and 30 from "sup".

The loading errors shouldn't happen. Maybe an older pytorch version could help here? We used version 4.1 originally. I hope that helps a bit!

**Comment by niphiwi** [comment]
I had the same missing key errors when loading the pre-trained models with `load_dict_state`. In DfpNet.py I replaced `layer2b` with `layer2x`. I guess the pre-trained models were trained with an older definition of TurbNetG.
