### ISSUE TITLE
Links to pre-trained models do not work

### ISSUE THREAD

**Issue by MinghuiS** [thunil/Deep-Flow-Prediction#6]
Hi,

The download links to the two pre-trained models seemed to not work. Could you take a look?

Thank you!

**Comment by thunil** [comment]
Hi, do you mean 
https://ge.in.tum.de/download/2019-deepFlowPred/model_data05_exp50 and
https://ge.in.tum.de/download/2019-deepFlowPred/model_mata10_exp70 ?
I just tested, both work fine on my side...

**Comment by MinghuiS** [comment]
> Hi, do you mean
> https://ge.in.tum.de/download/2019-deepFlowPred/model_data05_exp50 and
> https://ge.in.tum.de/download/2019-deepFlowPred/model_mata10_exp70 ?
> I just tested, both work fine on my side...

Thanks for your reply. Somehow I still see garbled text when I open the links.

**Comment by niphiwi** [comment]
@MinghuiS The links are fine. You see garbled text, because you would have to load the model with PyTorch (see: https://pytorch.org/tutorials/beginner/saving_loading_models.html) 
:-)

**Comment by MinghuiS** [comment]
Figured it out. Thanks for your reply 👍
