### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DfpNet:

### ISSUE THREAD

**Issue by michaeljehan** [thunil/Deep-Flow-Prediction#9]
<img width="562" alt="Screen Shot 2021-10-23 at 5 48 29 PM" src="https://user-images.githubusercontent.com/68639241/138553067-ceec0f9c-4c24-4a13-a52d-30121cb22a8f.png">
I was running the testcpu.py, but encountered this error. What is the best way to solve this issue?

**Comment by aalksii** [comment]
Hi! Yes, there is some mismatch of the layer name, check [this](https://github.com/thunil/Deep-Flow-Prediction/pull/10/commits/2c66f5ca14ab5563047af9e3796ee10496f25f10) thing.

**Comment by thunil** [comment]
Should be fixed
